### ISSUE TITLE
Add method to AuthZChecker that determines the least privileged permission for a path

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/kibali#17]
There are concerns that the ambiguity between Calendar.Read.All and Calendar.ReadWrite.All what both have a least privileged permission for `/me/calendars/{id}` will make it impossible to determine which is the least privileged permission.  Let's write the code to prove it can be done.

**Comment by wandeg** [comment]
@darrelmiller the changes introduced to generate the permissions table should enable us to do this https://github.com/microsoftgraph/kibali/pull/10
We have to track the least privilege permission so that we can generate the table.

**Comment by wandeg** [comment]
Resolved in https://github.com/microsoftgraph/kibali/pull/23.
