### ISSUE TITLE
Incorrect least privilege permission in the JSON model

### ISSUE THREAD

**Issue by njaci1** [microsoftgraph/kibali#64]
These two tables have been identified to be having incorrect least privilege permission.
https://learn.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-1.0&tabs=http
https://learn.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-1.0&tabs=http

**Comment by millicentachieng** [comment]
This was resolved
