### ISSUE TITLE
Investigate why the latest release changes the order of permissions in the higher privileged permissions column.

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/kibali#85]

**Comment by millicentachieng** [comment]
This is caused by the change that happened on the line below. https://github.com/microsoftgraph/kibali/blob/55af63456b1d7adee2babe1a456e68ea1ceea21b/src/kibali/ProtectedResource.cs#L409

Was this necessary? Can it be removed?

**Comment by andrueastman** [comment]
Any chance you can share a difference between the current result and the desired result?

**Comment by wandeg** [comment]
For starters the ordering change resulted in a huge diff making it difficult to verify actual permission changes. Working on reverting this

**Comment by millicentachieng** [comment]
@andrueastman See the PR that was generated with the update.
https://github.com/microsoftgraph/microsoft-graph-docs/pull/24919
