### ISSUE TITLE
Some permissions are listed in both the higher privilege permissions column and least privilege permissions column

### ISSUE THREAD

**Issue by millicentachieng** [microsoftgraph/kibali#87]
<img width="670" alt="image" src="https://github.com/user-attachments/assets/985558b7-da1f-4a2d-a523-0e12bb17c520">

There's also a hanging `and` in the least privileged permissions column.

**Comment by wandeg** [comment]
Caused by a duplicate in the permission files. The fix to the files is present but we can add a change to Kibali to ensure we catch such issues

**Comment by millicentachieng** [comment]
@wandeg What about the hanging `and`?

**Comment by millicentachieng** [comment]
Fixed by https://github.com/microsoftgraph/kibali/pull/89
